[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov-config pyproject.toml {args:test/unit test/test_copyright_headers.py}"
test-installer = "pytest --no-cov {args:test/installer} -vvv"
typing = "mypy {args:src test}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

[[envs.all.matrix]]
python = ["3.9", "3.10", "3.11", "3.12"]

[envs.integ]
pre-install-commands = [
  "pip install -r requirements-integ-testing.txt",
  "pip install -r requirements-testing.txt",
]

[envs.integ.scripts]
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1"
test_submitters = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m submitter"
test_adaptors = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m adaptor"

[envs.integ-ci]
pre-install-commands = [
  "pip install -r requirements-integ-testing.txt",
  "pip install -r requirements-testing.txt",
]

[[envs.integ-ci.matrix]]
max = ["2024"]
python = ["3.10"]

[[envs.integ-ci.matrix]]
max = ["2025"]
python = ["3.11"]

[[envs.integ-ci.matrix]]
max = ["2026"]
python = ["3.11"]

[envs.integ-ci.env-vars]
MAX_VERSION = "{matrix:max}"

[envs.integ-ci.scripts]
setup = "python ./pipeline/setup-runner.py --versions {matrix:max} {args}"
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1"

[envs.release]
detached = true

[envs.release.scripts]
deps = "pip install -r requirements-release.txt"
bump = "semantic-release -v --strict version --no-push --no-commit --no-tag --skip-build {args}"
version = "semantic-release -v --strict version --print {args}"

[envs.installer.scripts]
build-installer = "python {root}/scripts/build_installer_cli.py --installer-source-path {root}/installer/DeadlineCloudFor3dsMaxSubmitter.xml {args:}"