# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
"""
3ds Max Command-Line Render task driver.

Runs on the worker for each task. Reads Deadline Cloud path-mapping rules,
generates a pre-render MAXScript that remaps the scene's asset paths to their
session locations, then invokes 3dsmaxcmd.exe to render the task's frame chunk.

3dsmaxcmd.exe (not 3dsmaxbatch.exe) is used deliberately: it registers as a
render server, which network-licensed plugins such as Pencil+ (NTR) require to
render without a watermark.

Parameter values (Param, Task, and Session) are passed in as command-line
arguments by the OpenJD template rather than interpolated into the script
source, so values such as a Windows path ending in a backslash or containing a
quote can't break the task script's parsing. ``main()`` parses those args; the
helper functions stay pure and testable.
"""

import argparse
import json
import os
import subprocess
import sys


def normalize_path(path: str) -> str:
    """Convert backslashes to forward slashes (3ds Max accepts forward slashes)."""
    return path.replace("\\", "/")


def load_path_mapping_rules(rules_file: str) -> "list[tuple[str, str]]":
    """
    Read Deadline Cloud path-mapping rules into a list of (source, dest) pairs.

    Returns an empty list if the rules file is missing or unparseable — in that
    case the render proceeds with the scene's original paths (correct when the
    worker already sees assets at their original locations, e.g. re-mounted
    storage-profile drives).
    """
    if not rules_file or not os.path.exists(rules_file):
        return []
    try:
        with open(rules_file, "r") as fh:
            data = json.load(fh)
    except (OSError, ValueError) as exc:
        print(f"Warning: could not read path mapping rules {rules_file}: {exc}")
        return []

    rules: "list[tuple[str, str]]" = []
    for rule in data.get("path_mapping_rules", []):
        source = rule.get("source_path", "")
        dest = rule.get("destination_path", "")
        if source and dest:
            rules.append((source, dest))
    return rules


def _escape_maxscript_string(value: str) -> str:
    r"""Escape a string for embedding inside a MAXScript double-quoted literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build_prerender_maxscript(
    rules: "list[tuple[str, str]]", output_dir: str = "", output_filename: str = ""
) -> str:
    """
    Build a MAXScript that remaps the loaded scene's asset paths.

    For each (source, dest) rule, an asset path whose prefix matches ``source``
    *at a path boundary* is rewritten to ``dest`` plus the original remainder.
    The prefix must be the whole path or be followed by ``/`` so a rule for
    ``L:/tex`` does not also capture ``L:/textures/...``. Matching is
    case-insensitive and slash-insensitive (Windows paths), while the
    remainder's original case is preserved.

    Covers bitmap textures and XRef scene files. Assets whose paths don't match
    any rule are left untouched.

    Render element outputs (e.g. the Pencil+ Line pass) are handled separately:
    when ``output_dir`` is given, each render element is redirected into that
    directory keeping its own filename (preserving frame-number tokens). Their
    baked absolute paths are not covered by a path-mapping rule (Deadline only
    creates rules for input roots, not output-only directories), so remapping
    them by rule would leave them pointing at the artist's disk and 3dsmaxcmd
    would abort writing there (error 0x3). Redirecting to the job output
    directory guarantees a writable, captured location. Because that redirect
    keeps only each element's basename, two elements whose scene paths share a
    basename (e.g. ``beauty/render.exr`` and ``line/render.exr``) would collide;
    the generated script tracks claimed basenames (seeded with the main output)
    and, only on a collision, inserts the element index before the extension
    (``render_re1.exr``) so sequence-mode frame padding still composes.
    """
    pair_literals = []
    for source, dest in rules:
        norm_source = normalize_path(source).lower()
        pair_literals.append(
            f'    #("{_escape_maxscript_string(norm_source)}", '
            f'"{_escape_maxscript_string(normalize_path(dest))}")'
        )
    pairs_block = ",\n".join(pair_literals)

    output_dir_literal = _escape_maxscript_string(normalize_path(output_dir)) if output_dir else ""
    output_filename_literal = _escape_maxscript_string(output_filename) if output_filename else ""

    return f"""(
    -- Auto-generated by maxcmd_render.py. Remaps scene asset paths for the
    -- Deadline Cloud session before 3dsmaxcmd renders.
    -- MAXScript requires all 'local' declarations at the top of their block.
    local remaps = #(
{pairs_block}
    )
    -- Job output directory (session-mapped). Render element outputs are
    -- redirected here so they land in a writable, captured location.
    local jobOutputDir = "{output_dir_literal}"
    -- Basenames already claimed under jobOutputDir (the main output plus any
    -- prior render elements), lower-cased for case-insensitive collision
    -- checks (Windows filesystems are case-insensitive). Two elements whose
    -- scene paths share a basename (e.g. beauty/render.exr and line/render.exr)
    -- would otherwise flatten to the same jobOutputDir/render.exr.
    local usedNames = #()
    -- Seed with the -outputName beauty-pass filename (passed from the driver)
    -- so a render element whose basename matches can't clobber the main output.
    -- When no -outputName is used (blank Output Filename), this is empty and
    -- the rendOutputFilename seed below provides the fallback coverage instead.
    local cmdOutputName = "{output_filename_literal}"
    if cmdOutputName != "" then (
        append usedNames (toLower cmdOutputName)
    )

    fn _normPath p = (
        toLower (substituteString p "\\\\" "/")
    )

    fn _remapPath p = (
        local np, src, tail, result
        result = p
        if p != undefined and p != "" then (
            np = _normPath p
            for pair in remaps while result == p do (
                src = pair[1]
                if (matchPattern np pattern:(src + "*")) then (
                    -- Require the prefix to end at a path boundary so a rule
                    -- for "L:/tex" does not also capture "L:/textures/...".
                    -- The match is valid only when the source is the whole
                    -- path or is followed by a path separator.
                    tail = substring np (src.count + 1) (-1)
                    if (tail == "" or tail[1] == "/") then (
                        result = pair[2] + (substring p (src.count + 1) (-1))
                    )
                )
            )
        )
        result
    )

    -- Each section is wrapped in try/catch. 3dsmaxcmd surfaces an unhandled
    -- MAXScript error in a pre-render script as a fatal "unexpected exception
    -- has occurred in the network renderer" and aborts the whole render.
    -- Catching per section means a failure remapping one asset type (e.g. an
    -- XRef that fails to reload) is logged and the render still proceeds.
    try (
        for tex in (getClassInstances Bitmaptexture) do (
            local origFn, mappedFn
            origFn = tex.filename
            if origFn != undefined and origFn != "" then (
                mappedFn = _remapPath origFn
                if mappedFn != origFn then (
                    tex.filename = mappedFn
                    format "maxcmd path map: % -> %\\n" origFn mappedFn
                )
            )
        )
    ) catch (
        format "maxcmd path map: bitmap remap error (continuing): %\\n" (getCurrentException())
    )

    try (
        for i = 1 to (xrefs.getXRefFileCount()) do (
            local xf, origFn, mappedFn
            xf = xrefs.getXRefFile i
            if xf != undefined and xf.filename != undefined then (
                origFn = xf.filename
                mappedFn = _remapPath origFn
                if mappedFn != origFn then (
                    xf.filename = mappedFn
                    format "maxcmd path map: % -> %\\n" origFn mappedFn
                )
            )
        )
    ) catch (
        format "maxcmd path map: xref remap error (continuing): %\\n" (getCurrentException())
    )

    -- Remap the main render output path and make sure its directory exists.
    -- 3dsmaxcmd does not create missing output directories, so an unmapped or
    -- newly-mapped path whose folder is absent aborts the render (error 0x3).
    --
    -- When no -outputName is passed (blank Output Filename), 3dsmaxcmd falls
    -- back to this scene-baked path. Its directory is output-only, so Deadline
    -- creates no path-mapping rule for it and a rule-based remap would leave it
    -- on the artist's disk (0x3 abort, or written outside the captured output).
    -- So redirect it to the job output directory (keeping the scene's filename)
    -- exactly like render elements, and only fall back to rule-based remap when
    -- no job output directory is available.
    try (
        if rendOutputFilename != undefined and rendOutputFilename != "" then (
            if jobOutputDir != "" then (
                rendOutputFilename = jobOutputDir + "/" + (filenameFromPath rendOutputFilename)
            ) else (
                rendOutputFilename = _remapPath rendOutputFilename
            )
            makeDir (getFilenamePath rendOutputFilename) all:true
            -- Claim the (redirected) beauty-pass basename so a render element
            -- can't clobber it.
            append usedNames (toLower (filenameFromPath rendOutputFilename))
        )
    ) catch (
        format "maxcmd output map: main output remap error (continuing): %\\n" (getCurrentException())
    )

    -- Remap render element output paths and ensure their directories exist.
    -- Render elements (including Pencil+ Line output) carry their own baked
    -- absolute paths that are independent of the main render output.
    --
    -- Scope: this is a path-correctness fix only. It keeps each element's
    -- scene-authored filename and just forces the folder to the job output
    -- directory so the write succeeds (avoids the 0x3 "path not found" abort)
    -- and is captured by job attachments. Full render-element support for the
    -- command-line flow (adaptor-style "<output_name>_<element>" naming,
    -- per-element config/UI, ignore lists) is intentionally deferred to a
    -- follow-up PR. This applies to every render element in the scene, not
    -- just Pencil+, since any baked element path would fail the same way.
    try (
        local reMgr, reIdx, reFn, reMapped, baseName
        reMgr = maxOps.GetCurRenderElementMgr()
        if reMgr != undefined then (
            for reIdx = 0 to (reMgr.NumRenderElements() - 1) do (
                reFn = reMgr.GetRenderElementFilename reIdx
                if reFn != undefined and reFn != "" then (
                    -- Redirect to the job output directory (keeping the
                    -- element's own filename, so frame-number tokens survive)
                    -- when one is set; otherwise fall back to rule-based remap.
                    if jobOutputDir != "" then (
                        baseName = filenameFromPath reFn
                        -- Disambiguate on a basename collision so two elements
                        -- (e.g. beauty/render.exr and line/render.exr) don't
                        -- flatten to the same file. The index goes before the
                        -- extension so 3dsmaxcmd's sequence-mode frame padding
                        -- still composes correctly (render_re1.exr renders as
                        -- render_re10001.exr). reIdx is unique per element, so
                        -- a single pass suffices.
                        if (findItem usedNames (toLower baseName)) != 0 then (
                            baseName = (getFilenameFile baseName) + "_re" + (reIdx as string) + (getFilenameType baseName)
                        )
                        append usedNames (toLower baseName)
                        reMapped = jobOutputDir + "/" + baseName
                    ) else (
                        reMapped = _remapPath reFn
                    )
                    reMgr.SetRenderElementFilename reIdx reMapped
                    makeDir (getFilenamePath reMapped) all:true
                    format "maxcmd output map: % -> %\\n" reFn reMapped
                )
            )
        )
    ) catch (
        format "maxcmd output map: render element remap error (continuing): %\\n" (getCurrentException())
    )
    OK
)
"""


def run_maxcmd(cmd: "list[str]") -> int:
    """
    Run 3dsmaxcmd, streaming its output as sanitized UTF-8, and return its exit code.

    3dsmaxcmd emits banner text that is not valid UTF-8 (plugin/version notices
    with characters like superscripts). If those raw bytes reach a strict UTF-8
    reader — e.g. the worker's stdout consumer — the reader thread crashes and
    the task is marked failed even though the render succeeded. To prevent that,
    we capture 3dsmaxcmd's output, decode it with ``errors="replace"``, and
    re-emit it as valid UTF-8 so the exit code reflects the actual render result.
    """
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    assert process.stdout is not None
    for raw_line in process.stdout:
        # Decode tolerantly, then reduce to ASCII so the output is safe for any
        # downstream consumer regardless of its console/log encoding (a Windows
        # cp1252 console cannot encode the U+FFFD replacement char). 3dsmaxcmd
        # banner decorations become '?'; all real log content is ASCII.
        text = raw_line.decode("utf-8", errors="replace")
        safe = text.encode("ascii", errors="replace").decode("ascii")
        print(safe, end="", flush=True)
    return process.wait()


def dump_max_network_log() -> None:
    """
    Print the 3ds Max network render log (Max.log) for diagnostics.

    3dsmaxcmd renders via the network renderer, which writes detailed error
    information (MAXScript exceptions, missing output paths, plugin/license
    failures) to a per-user Max.log that never reaches stdout. On a failed
    render the terse stdout ("unexpected exception has occurred in the network
    renderer") is not enough to diagnose the cause, so surface the log here.
    """
    import glob

    local_appdata = os.environ.get("LOCALAPPDATA", "")
    if not local_appdata:
        return
    pattern = os.path.join(local_appdata, "Autodesk", "3dsMax", "*", "ENU", "Network", "Max.log")
    matches = glob.glob(pattern)
    if not matches:
        print("No Max network log (Max.log) found for diagnostics.")
        return
    log_file = max(matches, key=os.path.getmtime)
    print(f"--- Begin Max network log ({log_file}) ---")
    try:
        with open(log_file, "r", encoding="utf-8", errors="replace") as fh:
            print(fh.read().encode("ascii", errors="replace").decode("ascii"))
    except OSError as exc:
        print(f"Could not read Max network log {log_file}: {exc}")
    print("--- End Max network log ---")


def build_maxcmd_command(
    executable: str,
    scene_file: str,
    start_frame: int,
    end_frame: int,
    prerender_script: str,
    camera: str = "",
    output_path: str = "",
) -> "list[str]":
    """
    Build the 3dsmaxcmd.exe command line for a frame chunk.

    Uses ``-preRenderScript`` to apply path mapping to the loaded scene before
    rendering. ``-camera`` and ``-outputName`` are only added when provided;
    otherwise 3dsmaxcmd uses the scene's active view and Render Setup output.

    ``-outputName`` is passed as a plain stem (e.g. ``render.exr``) with no
    per-frame token. Because the driver always renders an explicit range
    (``-start:N -end:N``), 3ds Max renders in sequence mode and inserts the
    padded frame number itself (``render0001.exr``), so each per-frame task
    writes a distinct file. Injecting our own frame token here would
    double-number the output (``render0001.0001.exr``). Verified on a
    multi-frame Deadline Cloud render.
    """
    cmd = [
        executable,
        f"-start:{start_frame}",
        f"-end:{end_frame}",
    ]
    if camera:
        cmd.append(f"-camera:{camera}")
    if output_path:
        cmd.append(f"-outputName:{output_path}")
    if prerender_script:
        cmd.append(f"-preRenderScript:{prerender_script}")
    cmd.append(scene_file)
    return cmd


def parse_args(argv: "list[str] | None" = None) -> argparse.Namespace:
    """Parse the task parameters passed as command-line arguments."""
    parser = argparse.ArgumentParser(description="3ds Max command-line render task driver.")
    parser.add_argument("--executable", default="3dsmaxcmd")
    parser.add_argument("--scene-file", required=True)
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--output-file-name", default="")
    parser.add_argument("--camera", default="")
    parser.add_argument("--frame", type=int, required=True)
    parser.add_argument("--rules-file", default="")
    return parser.parse_args(argv)


def main(argv: "list[str] | None" = None) -> int:
    args = parse_args(argv)
    executable = args.executable
    scene_file = normalize_path(args.scene_file)
    output_dir = normalize_path(args.output_dir)
    output_file_name = args.output_file_name
    camera = args.camera
    # One task renders one frame; OpenJD expands the frame range into a task
    # per frame, so start and end are the same frame here.
    frame = args.frame
    start_frame = end_frame = frame
    rules_file = normalize_path(args.rules_file)

    print(f"Rendering frame {frame} of scene {scene_file}")

    if not os.path.exists(scene_file):
        print(f"ERROR: scene file not found: {scene_file}", file=sys.stderr)
        return 1

    # Generate the pre-render path-mapping MAXScript next to the driver.
    rules = load_path_mapping_rules(rules_file)
    print(f"Loaded {len(rules)} path mapping rule(s)")
    prerender_script = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "maxcmd_prerender.ms"
    )
    prerender_body = build_prerender_maxscript(
        rules, output_dir=output_dir, output_filename=output_file_name
    )
    with open(prerender_script, "w") as fh:
        fh.write(prerender_body)

    # Resolve the output target (directory + filename) if a name was provided.
    # The filename is passed as a plain stem; 3ds Max inserts the per-frame
    # number itself (sequence mode from -start/-end), so distinct frames don't
    # collide. See build_maxcmd_command for details.
    output_path = ""
    if output_file_name:
        os.makedirs(output_dir, exist_ok=True)
        output_path = normalize_path(os.path.join(output_dir, output_file_name))

    cmd = build_maxcmd_command(
        executable,
        scene_file,
        start_frame,
        end_frame,
        normalize_path(prerender_script),
        camera=camera,
        output_path=output_path,
    )
    print(f"Executing: {' '.join(cmd)}")

    try:
        returncode = run_maxcmd(cmd)
    except FileNotFoundError:
        print(f"ERROR: 3dsmaxcmd not found: {executable}", file=sys.stderr)
        return 1

    if returncode != 0:
        print(f"ERROR: 3dsmaxcmd failed with exit code {returncode}", file=sys.stderr)
        # Surface the detail behind the terse "unexpected exception" message:
        # the generated pre-render script and the Max network log.
        print("--- Begin generated pre-render MAXScript ---")
        print(prerender_body)
        print("--- End generated pre-render MAXScript ---")
        dump_max_network_log()
    return returncode


if __name__ == "__main__":
    sys.exit(main())
